### ISSUE TITLE
Please add support for Font Awesome Pro 5

### ISSUE THREAD

**Issue by meniam** [dhardtke/font-awesome-minify-plugin#3]
Font awesome pro has brands.css, regular.css, solid.css and **light.css** icon versions.
Your code supports only brands, regular and solid, please add "light" to this regexp: 

else if (/(solid|regular|brands)\.css/.test(data.resource))

**Comment by dhardtke** [comment]
Thanks for your suggestion. While I do not have access to FA Pro, I do hope it works in version 1.0.7 that I just released.

If not, please just open another issue. :)
